Unify jobs that run on push

diff --git a/.github/workflow.templates/js-search.yml b/.github/workflow.templates/js-search.yml
--- a/.github/workflow.templates/js-search.yml
+++ b/.github/workflow.templates/js-search.yml
@@ -1,12 +1,13 @@
 #@ load("cache.lib.yml", "cache_node")
 
-name: JS-Search tests
+name: Cheks
 
 "on":
   - push
 
 jobs:
-  test:
+  js-search-test:
+    name: JS-Search tests
     runs-on: ubuntu-latest
     timeout-minutes: 10
     permissions:
@@ -34,3 +35,26 @@ jobs:
           reporter: jest-junit
       - name: Build js-search
         run: cd pkg/js-search/ && rushx build
+  lint-and-typecheck:
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    permissions:
+      id-token: write
+      contents: read
+      checks: write
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
+        with:
+          node-version: "16"
+      - #@ cache_node()
+      - name: Add local rush scripts to PATH
+        run: echo "${PWD}"/common/scripts >> $GITHUB_PATH
+      - name: Install and build packages
+        run: rush update && rush build
+      - name: Lint all the packages
+        run: rush lint:strict
+      - name: Typecheck all the packages
+        #! Run typecheck even if linting fails
+        if: success() || failure()
+        run: rush typecheck
