Revert formatting of ci workflows to tab width 2

diff --git a/.github/workflow.templates/on-push.yml b/.github/workflow.templates/on-push.yml
--- a/.github/workflow.templates/on-push.yml
+++ b/.github/workflow.templates/on-push.yml
@@ -7,109 +7,109 @@
 name: Checks
 
 "on":
-    push:
-        branches-ignore:
-            - "ci-debug/*"
+  push:
+    branches-ignore:
+      - "ci-debug/*"
 
 jobs:
-    js-search-test: #@ test_job("JS-Search Tests", "pkg/js-search", "jest-junit")
+  js-search-test: #@ test_job("JS-Search Tests", "pkg/js-search", "jest-junit")
 
-    ui-test: #@ test_job("UI Tests", "pkg/ui")
+  ui-test: #@ test_job("UI Tests", "pkg/ui")
 
-    web-client-test: #@ test_job("Web Client Tests", "apps/web-client")
+  web-client-test: #@ test_job("Web Client Tests", "apps/web-client")
 
-    db-test: #@ test_job("DB Tests", "pkg/db")
+  db-test: #@ test_job("DB Tests", "pkg/db")
 
-    e2e-test:
-        timeout-minutes: 60
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v3
-            - uses: actions/setup-node@v3
-              with:
-                  node-version: "16"
-            -  #@ cache_node()
-            -  #@ rush_add_path()
-            -  #@ rush_install()
-            -  #@ rush_build()
-            - name: Build the app
-              run: cd apps/web-client && rushx build:prod
-            - name: Run Playwright tests
-              run: cd apps/e2e && rushx test:ci
-            - uses: actions/upload-artifact@v3
-              if: always()
-              with:
-                  name: playwright-test-results
-                  path: apps/e2e/test-results
-                  retention-days: 30
+  e2e-test:
+    timeout-minutes: 60
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+      -  #@ cache_node()
+      -  #@ rush_add_path()
+      -  #@ rush_install()
+      -  #@ rush_build()
+      - name: Build the app
+        run: cd apps/web-client && rushx build:prod
+      - name: Run Playwright tests
+        run: cd apps/e2e && rushx test:ci
+      - uses: actions/upload-artifact@v3
+        if: always()
+        with:
+          name: playwright-test-results
+          path: apps/e2e/test-results
+          retention-days: 30
 
-    lint-and-typecheck:
-        runs-on: ubuntu-latest
-        timeout-minutes: 10
-        permissions:
-            id-token: write
-            contents: read
-            checks: write
-        steps:
-            - uses: actions/checkout@v3
-            - uses: actions/setup-node@v3
-              with:
-                  node-version: "16"
-            -  #@ cache_node()
-            -  #@ rush_add_path()
-            -  #@ rush_install()
-            -  #@ rush_build()
-            - name: Lint all the packages
-              run: rush lint:strict
-            - name: Typecheck all the packages
-              #! Run typecheck even if linting fails
-              if: success() || failure()
-              run: rush typecheck
+  lint-and-typecheck:
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    permissions:
+      id-token: write
+      contents: read
+      checks: write
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+      -  #@ cache_node()
+      -  #@ rush_add_path()
+      -  #@ rush_install()
+      -  #@ rush_build()
+      - name: Lint all the packages
+        run: rush lint:strict
+      - name: Typecheck all the packages
+        #! Run typecheck even if linting fails
+        if: success() || failure()
+        run: rush typecheck
 
-    perform-monorepo-checks:
-        runs-on: ubuntu-latest
-        timeout-minutes: 10
-        steps:
-            - uses: actions/checkout@v3
-              with:
-                  fetch-depth: 0
-            - uses: actions/setup-node@v3
-              with:
-                  node-version: "16"
-            -  #@ cache_node()
-            -  #@ rush_add_path()
-            -  #@ rush_install()
-            -  #@ rush_build()
-            - name: Check for unlisted artifacts in 'apps' and 'pkg' folders
-              run: rush check-workspace-projects
+  perform-monorepo-checks:
+    runs-on: ubuntu-latest
+    timeout-minutes: 10
+    steps:
+      - uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+      -  #@ cache_node()
+      -  #@ rush_add_path()
+      -  #@ rush_install()
+      -  #@ rush_build()
+      - name: Check for unlisted artifacts in 'apps' and 'pkg' folders
+        run: rush check-workspace-projects
 
-    deploy-production:
-        name: Deploy web-client app to bunny cdn
-        runs-on: ubuntu-latest
-        steps:
-            - uses: actions/checkout@v3
-            - uses: actions/setup-node@v3
-              with:
-                  node-version: "16"
-            -  #@ cache_node()
-            -  #@ rush_add_path()
-            -  #@ rush_install()
-            -  #@ rush_build()
-            - name: Build web-client app using prefix ${{ github.head_ref || github.ref_name }}
-              run: cd apps/web-client && rushx build:prod
-              env:
-                  BASE_PATH: /${{ github.head_ref || github.ref_name }}
-            - name: Install ncftp
-              run: |
-                  sudo apt-get update
-                  sudo apt-get install ncftp
-            - name: Copy built app to bunny storage zone
-              run: ncftpput -R -v -u librocco -p "${BUNNY_STORAGE_PASSWORD}" -m storage.bunnycdn.com ${{ github.head_ref || github.ref_name }} apps/web-client/build/*
-              env:
-                  BUNNY_STORAGE_PASSWORD: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
-            - name: Purge bunny cache
-              run: 'curl --request POST --url https://api.bunny.net/pullzone/1306302/purgeCache --header "content-type: application/json" --header "AccessKey: $BUNNY_API_KEY"'
-              env:
-                  BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
-            - name: Output link to deployed app
-              run: echo You can view the app on https://test.libroc.co/${{ github.head_ref || github.ref_name }}/index.html | tee -a $GITHUB_STEP_SUMMARY
+  deploy-production:
+    name: Deploy web-client app to bunny cdn
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v3
+      - uses: actions/setup-node@v3
+        with:
+          node-version: "16"
+      -  #@ cache_node()
+      -  #@ rush_add_path()
+      -  #@ rush_install()
+      -  #@ rush_build()
+      - name: Build web-client app using prefix ${{ github.head_ref || github.ref_name }}
+        run: cd apps/web-client && rushx build:prod
+        env:
+          BASE_PATH: /${{ github.head_ref || github.ref_name }}
+      - name: Install ncftp
+        run: |
+          sudo apt-get update
+          sudo apt-get install ncftp
+      - name: Copy built app to bunny storage zone
+        run: ncftpput -R -v -u librocco -p "${BUNNY_STORAGE_PASSWORD}" -m storage.bunnycdn.com ${{ github.head_ref || github.ref_name }} apps/web-client/build/*
+        env:
+          BUNNY_STORAGE_PASSWORD: ${{ secrets.BUNNY_STORAGE_PASSWORD }}
+      - name: Purge bunny cache
+        run: 'curl --request POST --url https://api.bunny.net/pullzone/1306302/purgeCache --header "content-type: application/json" --header "AccessKey: $BUNNY_API_KEY"'
+        env:
+          BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
+      - name: Output link to deployed app
+        run: echo You can view the app on https://test.libroc.co/${{ github.head_ref || github.ref_name }}/index.html | tee -a $GITHUB_STEP_SUMMARY
